language: python
python:
 - 3.7
script: pytest --cov-report term --cov
before_install:
 - "pip install -U pip"
 - "python setup.py install"
 - "pip install pytest-cov"
 - "pip install coverage[toml]"
 - "pip install coveralls"

after_success:
 - "coveralls"