[tool.coverage.paths]
source = ['handcalcs', '*/site-packages']

[tool.coverage.run]
branch = true
source = ['handcalcs']

[tool.coverage.report]
show_missing = true


[tool.poetry]
name = "handcalcs"
version = "1.0.0"
description = "Sample desc"
authors = ["Connor Ferster"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
pyparsing = "^2.4.7"

[tool.poetry.dev-dependencies]
pytest = "^5.4.3"
coverage = {extras = ["toml"], version = "^5.1"}
pytest-cov = "^2.9.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
